openapi: 3.0.2
# Revisions:
# 2019-05-09 initial version
# 2019-05-11 added nullable values to support patch
# 2019-05-17 TileRow and TileCol are now 'numbers' (not strings)
# 2019-05-17 "unless a different coordinate reference system is specified in the parameter `bbox-crs`." has been removed and instead we have added "unless a different coordinate         reference system is specified by another parameter in the API."
# 2019-05-21 "The default Tiling Scheme is the Google Maps Tiling Scheme" is changed to "The default Tiling Scheme is the WebMercatorQuad (sometimes refered as Google Maps Tiling Scheme)"

info:
  title: OGC API Building Blocks for maps and tiles
  description: |-
    Common components used in the OGC API maps and tiles standards.

    This document is also available in [GitHub](https://github.com/opengeospatial/OGC-API-Map-Tiles/tree/master/standard/openapi).

  version: "1.0.0"
  contact:
    name: Joan Maso
    email: joan.maso@uab.cat
  license:
    name: OGC License
    url: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/LICENSE'

components:
  responses:
    TileMatrixSets:
      description: |-
        An array of tile matrix sets (tiling schemes).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tileMatrixSets'
    tiles:
      description: |-
        Description of the tiles.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tiles'
  parameters:
    tileMatrixSetId:
      name: tileMatrixSetId
      in: path
      description: |-
        Identifier of a specific tiling scheme. It can be one of the specified in Annex D.1 of the OGC 17-083r2 standard or one defined in this service.
      required: false
      schema:
        type: string
      example: WebMercatorQuad
    tileMatrix:
      name: tileMatrix
      in: path
      description: |-
        Identifier selecting one of the scales defined in the TileMatrixSet and representing the scaleDenominator the tile. For example,
        Ireland is fully within the Tile at tileMatrix=5, tileRow=10 and tileCol=15.
      required: true
      schema:
        type: string
      example: '11'
    tileRow:
      name: tileRow
      in: path
      description: |-
        Row index of the tile on the selected TileMatrix. It cannot exceed the MatrixWidth-1 for the selected TileMatrix. For example, Ireland is fully within the Tile at tileMatrix=5, tileRow=10 and tileCol=15.
      required: true
      schema:
        type: integer
        minimum: 0
      example: '827'
    tileCol:
      name: tileCol
      in: path
      description: |-
        Column index of the tile on the selected TileMatrix. It cannot exceed the MatrixHeight-1 for the selected TileMatrix. For example, Ireland is fully within the Tile at tileMatrix=5, tileRow=10 and tileCol=15.
      required: true
      schema:
        type: integer
        minimum: 0
      example: 1231
    scaleDenominator:
      name: scaleDenominator
      in: query
      description: |-
         A range of scale denominators (that can be used to generate a list of tileMatrix names). Note that scale denominators have several significant digits. To prevent mistakes apply tolerances to intervals. If the client wants to specify a single scale denominator, it will use an small interval with enough tolerance.
      required: false
      style: form
      explode: false
      schema:
        type: array
        minItems: 2
        maxItems: 2
        items:
          type: number
          format: double
    multiTileType:
      name: multiTileType
      in: query
      description: |-
        When successful, the service will respond to a query in one of two ways. It can provide a file with links to each tile or or it will provide the tiles in a package. The package can still contain the description of each tile
        
        The allowed values for this parameter are `url`, `tiles` and `full`.
        If the value of the `multiTileType` parameter is set to `url` causes the server to return a list of the selected tiles in a format following the `tileSet` schema.  tile description in the list will contain a URL to download the tile later.
        If the value of the `multiTileType` parameter is set to `tiles` causes the server to return a package (e.g. a ZIP file) that will include tiles as separated parts in the package. 
        If the value of the `multiTileType` parameter is set to `full` causes the server to return the tiles and a list of the selected tiles in a format following the `tileSet` schema as part of a package. 
        The default value is `tiles`.
      style: form
      schema:
        type: string
        default: tiles
        enum:
          - url
          - tiles
          - full
      example: full
  examples:
    link-landingPage-tms-json:
      href: 'http://data.example.org/tileMatrixSet?f=json'
      rel: tileMatrixSets
      type: application/json
      title: List of tileMatrixSets implemented by this API in JSON
    link-landingPage-tms-html:
      href: 'http://data.example.org/tileMatrixSet?f=html'
      rel: tileMatrixSets
      type: text/html
      title: List of tileMatrixSets implemented by this API in HTML
    link-landingPage-tiles:
      href: 'http://data.example.org/tiles'
      rel: tiles
      type: application/json
      title: Link to information on tiles combining more than one collection
    link-collection-tiles:
      href: 'http://data.example.com/collections/buildings/tiles'
      rel: tiles
      type: 'application/json'
    link-tiles-this:
      href: 'http://data.example.com/collections/buildings/tiles'
      rel: self
      type: 'application/json'
    link-tiles-tile:
      href: 'http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png'
      rel: tile
      type: 'image/png'
    link-tiles-info:
      href: 'http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info'
      rel: info
      type: 'text/html'
    link-tiles-col-this:
      href: 'http://data.example.com/tiles'
      rel: self
      type: 'application/json'
    link-tiles-col-tile:
      href: 'http://data.example.com/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png'
      rel: tile
      type: 'image/png'
    link-tiles-col-info:
      href: 'http://data.example.com/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info'
      rel: info
      type: 'text/html'      
  schemas:
    collection-link:
      #This element is not directly linkable by other APIs because they probably will need to add other links to other resource types. Instead, it would be copied and enriched with more examples.
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/link'
          example:
            - $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/examples/link-collection-this'
            - $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/examples/link-collection-describedBy'
            - $ref: '#/components/examples/link-collection-tiles'
    tiles:
      # This object does not include the links element that should be added as and additional element using tiles-link      
      type: object
      required:
        - tileMatrixSetLinks
      properties:
        # A WMTS layer definition has id, title, description, keyword that are already defined in OWS Common
        # wgs84BoundingBox is the 'extent' that is already defined in OWS Common
        # boundingBox
        tileMatrixSetLinks:
          $ref: '#/components/schemas/tileMatrixSetLink-set'
        infoTemplates:
          type: array
          description: |-
            Supported valid templates for the info presentation
          items:
            type: string
            example:
              - table
              - record
    tileMatrixSets:
      type: array
      items:
        $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/id-link'
      example:
        - id: MyWebMercatorQuad
          title: My Google Maps Compatible for the World
          links:
            - href: 'https://data.example.org/tileMatrixSet/MyWebMercatorQuad'
              rel: tileMatrixSet
              type: 'application/json'
    tileMatrixSet:
      required:
        - identifier
      type: object
      properties:
        title:
          description: Title of this tile matrix set, normally used for display to a human
          type: string
          example: Google Maps Compatible for the World
        abstract:
          description: Brief narrative description of this tile matrix set, normally available for display to a human
          type: string
          example: The most common TileMatrixSet, used in most of the main IT map browsers. It was initially popularized by Google Maps
        keywords:
          description: Unordered list of one or more commonly used or formalized word(s) or phrase(s) used to describe this dataset
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/keyword'
        identifier:
          description: Tile matrix set identifier,
          type: string
          example: WebMercatorQuad
        supportedCRS:
          description: Reference to one coordinate reference system (CRS)
          type: string
          format: uri
          example: 'http://www.opengis.net/def/crs/EPSG/0/3857'
        wellKnownScaleSet:
          description: Reference to a well-known scale set
          type: string
          example: 'http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible'
        tileMatrix:
          description: Describes a scale level and its tile matrix
          type: array
          items:
            $ref: '#/components/schemas/tileMatrix'
    tileMatrix:
      type: object
      required:
        - identifier
        - scaleDenominator
        - topLeftCorner
        - tileWidth
        - tileHeight
        - matrixWidth
        - matrixHeight
      properties:
        title:
          description: Title of this tile matrix, normally used for display to a human
          type: string
          example: Google Maps Compatible for the World zoom level 3
        abstract:
          description: Brief narrative description of this tile matrix, normally available for display to a human
          type: string
          example: 'Google Maps Compatible zoom level 3 that is equivalent to a scale of 1:69885283.00358972 and has 19567.87924100512 meters of pixel size in the equator'
        keywords:
          description: keywords about the elements in the collection
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/keyword'
        identifier:
          description: Identifier selecting one of the scales defined in the TileMatrixSet and representing the scaleDenominator the tile.
          type: string
          example: '3'
        scaleDenominator:
          description: Scale denominator level of this tile matrix
          type: number
          example: 69885283.00358972
        topLeftCorner:
          description: Position in CRS coordinates of the top-left corner of this tile matrix
          type: array
          items:
            type: number
            format: double
          example:
            - -20037508.3427892
            - 20037508.3427892
        tileWidth:
          description: Width of each tile of this tile matrix in pixels
          type: number
          format: integer
          minimum: 1
          example: 256
        tileHeight:
          description: Height of each tile of this tile matrix in pixels
          type: number
          format: integer
          minimum: 1
          example: 256
        matrixHeight:
          description: Width of the matrix (number of tiles in width)
          type: number
          format: integer
          minimum: 1
          example: 8
        matrixWidth:
          description: Height of the matrix (number of tiles in height)
          type: number
          format: integer
          minimum: 1
          example: 8
    mapbox-vector-tile:
      type: string
      format: binary
    tileMatrixSetLink-set:
      description: |-
        This list tileMatrixSetLink as defined in OGC 17-083r2 supported by this collectionId.
      type: array
      items:
        $ref: '#/components/schemas/tileMatrixSetLink-entry'
    tileMatrixSetLink-entry:
      type: object
      required:
        - tileMatrixSet
      properties:
        tileMatrixSet:
          type: string
          example: 'WebMercatorQuad'
        tileMatrixSetURI:
          type: string
          format: uri
          example: 'http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad'
        tileMatrixSetLimits:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/tileMatrixSetLimits-entry'
    tileMatrixSetLimits-entry:
      type: object
      required:
        - tileMatrix
        - minTileRow
        - maxTileRow
        - minTileCol
        - maxTileCol
      properties:
        tileMatrix:
          type: string
          format: uri
          example: '5'
        minTileRow:
          type: number
          format: integer
          minimun: 0
          example: 0
        maxTileRow:
          type: number
          format: integer
          minimun: 0
          example: 1
        minTileCol:
          type: number
          format: integer
          minimun: 0
          example: 3
        maxTileCol:
          type: number
          format: integer
          minimun: 0
          example: 4
    tileSet:
      description: |-
        This is the response for a multiple tiles request.
      type: object
      required: tileSet
      properties:
        tileSet:
          type: array
          items:
            $ref: '#/components/schemas/tileSetEntry'
    tileSetEntry:
      description: |-
        This is an entry on a multiple tiles request.
      type: object
      required:
        - tileURL
        - tileMatrix
      properties:
        tileURL:
          type: string
          format: uri
          example: 'http://data.example.com/collections/buildings/tiles/WebMercatorQuad/0/0/0.png'
        tileMatrix:
          type: string
          example: 0
        tileRow:
          type: number
          example: 0
        tileCol:
          type: number
          example: 0
        width:
          type: number
          description: |-
            The width of the tile in rendering device pixels. If it exceeds the visual display area be should cut when displayed
          example: 256
        height:
          type: number
          description: |-
            The height of the tile in rendering device pixels. If it exceeds the visual display area be should cut when displayed
          example: 256
        top:
          type: number
          description: |-
            Vertical position from the top of the visual display area in pixels. Negative value means that the left side of the tile is outside the top-left corner of the display and should be cut when displayed
          example: -10
        left:
          type: number
          description: |-
            Horizontal position from the left of the visual display area in pixels. Negative value means that the left side of the tile is outside the top-left corner of the display and should be cut when displayed
          example: -20