openapi: 3.0.2
# Revisions:
# 2019-08-02 initial version
# 2019-08-24 Updated to version 0.8.0

info:
  description: STAC Domain
  version: '1.0.0'
  title: STAC Domain

components:
  schemas:
    stacItemImage:
      description: OGC API Image extension for STAC Item Adding some properties specific for imagery. (The proposed element `citation` has not been included because there is a properties/providers that can do the job partially)
      allOf:
      - $ref: '#/components/schemas/stacItem'
      - type: object
        properties:
          nativeBbox:
            type: object
            description: Native bounding box of the image. (TBC It could be better to use spatial/extent/bbox as an array of 4 coordinates to be consistent with the rest of the document and with OGC API commons)
            required:
            - minX
            - maxX
            - minY
            - maxY
            properties: 
              minX:
                type: number
                format: double
                example: 35.99601745605469
              maxX:
                type: number
                format: double
                example: 36.08110063620433
              minY:
                type: number
                format: double
                example: 32.50426061084722
              maxY:
                type: number
                format: double
                example: 32.57551891751058
              crs:
                type: string
                format: uri
                default: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
                example: 'http://www.opengis.net/def/crs/EPSG/0/4326'
          proposed-nativeBbox:
            description: Native bounding box of the image. (TBC It could be better to use spatial/extent/bbox as an array of 4 coordinates to be consistent with the rest of the document and with OGC API commons)
            type: object
            required: bbox
            properties:
              bbox:
                $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/bbox'
              crs:
                $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/crs'
          nominalResM: 
            description: Nominal resolution (in meters) of the image
            type: number
            format: double
            example: 0.5332085767116562
          cloudCover:
            description: Percentage of cloud cover
            type: number
            format: double
            example: 80.5
    stacItem:
      title: STAC Item
      description:  
        This object represents the metadata for an item in a SpatioTemporal Asset Catalog.
        This schema is deaply inspired on https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md
        Changes
        The link definition has been replaced by the one in OGC API Common.
        The https://geojson.org/schema/Feature.json has been replaced by the GeoJSON geometry description in OGC API features.
      type: object
      allOf:
      - $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-features/1.0.0#/components/schemas/featureGeoJSON'
      - type: object
        required:
        - stac_version
        - id
        - geometry
        - links
        - assets
        - bbox
        - properties
        properties:
          stac_version:
            title: STAC version
            type: string
            const: 0.8.0
            example: 0.8.0
          stac_extensions:
            title: STAC extensions
            type: array
            uniqueItems: true
            items:
              anyOf:
              - title: Reference to a JSON Schema
                type: string
                format: uri
              - title: Reference to a core extension
                type: string
                enum:
                - checksum
                - cube
                - datetime-range
                - eo
                - label
                - pointcloud
                - sar
                - scientific
          id:
            title: Provider ID
            description: Provider item ID
            type: string
            example: LC81530252014153LGN00
          links:
            title: Item links
            description: Links to item relations
            type: array
            items:
              $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/link'
            example:
              - rel: self
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00.json"
              - rel: alternate
                href: "https://landsatonaws.com/L8/153/025/LC81530252014153LGN00"
                type: text/html
              - rel: root
                href: "http://landsat-pds.s3.amazonaws.com/L8/L1T-collection.json"
          assets:
            title: Asset links
            description: Links to assets
            type: object
            #Next code has been commented to prevent a Error in the Swagger HUB
            #patternProperties:
            #  ".+":
            #    $ref: '#/components/schemas/stacAsset'
            additionalProperties: false
            example: 
              thumbnail:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_thumb_large.jpg"
                type: image/jpeg
              metadata:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_MTL.txt"
                type: mtl
              B1:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B1.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 0
              B2:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B2.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 1
              B3:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B3.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 2
              B4:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B4.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 3
              B5:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B5.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 4
              B6:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B6.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 5
              B7:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B7.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 6
              B8:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B8.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 7
              B9:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B9.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 8
              B10:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B10.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 9
              B11:
                href: "http://landsat-pds.s3.amazonaws.com/L8/153/025/LC81530252014153LGN00/LC81530252014153LGN00_B11.TIF"
                type: image/vnd.stac.geotiff
                eo:bands:
                - 10            
          properties:
            type: object
            required:
            - datetime
            properties:
              datetime:
                title: Date and Time
                description: 'The searchable date/time of the assets, in UTC (Formatted in
                  RFC 3339) '
                type: string
                format: date-
                example: '2019-05-21T19:36:44Z'
              title:
                title: Item Title
                description: A human-readable title describing the item.
                type: string
                example: One image
              license:
                title: Item Licenses
                type: string
                example: propietary
              providers:
                $ref: '#/components/schemas/stacProviders'
              created:
                title: Metadata updated at
                type: string
                format: date-time
                example: '2019-06-21T19:36:44Z'
              updated:
                title: Metadata updated at
                type: string
                format: date-time
                example: '2019-08-21T19:36:44Z'
          collection:
            title: Collection ID
            description: The ID of the STAC Collection this Item references to.
            type: string
            example: Landsat8
    stacCollection:
      title: STAC Collection Specification
      description:  
        This object represents Collections in a SpatioTemporal Asset Catalog. Stac Collection is described in https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md
        This schema is a replica of https://raw.githubusercontent.com/radiantearth/stac-spec/master/collection-spec/json-schema/collection.json
      type: object
      allOf:
        - $ref: '#/components/schemas/stacCatalogue'
        - title: STAC Collection
          description: These are the fields specific to a STAC Collection. All other fields
            are inherited from STAC Catalog.
          type: object
          required:
          - license
          - extent
          properties:
            stac_extensions:
              title: STAC extensions
              type: array
              uniqueItems: true
              items:
                anyOf:
                - title: Reference to a JSON Schema
                  type: string
                  format: uri
                - title: Reference to a core extension
                  type: string
                  enum:
                  - asset
                  - checksum
                  - scientific
              example: []
            keywords:
              title: Keywords
              type: array
              items:
                type: string
              example: Daraa
            version:
              title: Collection Version
              type: string
              example: 1.0.0
            license:
              title: Collection License Name
              type: string
              example: proprietary
            providers:
              $ref: '#/components/schemas/stacProviders'
            extent:
              title: Extents
              type: object
              required:
              - spatial
              - temporal
              properties:
                spatial:
                  title: Spatial extent object
                  type: object
                  required:
                  - bbox
                  properties:
                    bbox:
                      title: Spatial extents
                      type: array
                      minItems: 1
                      items:
                        title: Spatial extent
                        type: array
                        minItems: 4
                        maxItems: 6
                        items:
                          type: number
                  example:
                    bbox:
                    - 35.99601745605469
                    - 32.50426061084722
                    - 36.08110063620433
                    - 32.72028872300039
                temporal:
                  title: Temporal extent object
                  type: object
                  required:
                  - interval
                  properties:
                    interval:
                      title: Temporal extents
                      type: array
                      minItems: 1
                      items:
                        title: Temporal extent
                        type: array
                        minItems: 2
                        maxItems: 2
                        items:
                          type:
                          - string
                          - 'null'
                          format: date-time
                  example:
                    interval:
                    - '2019-05-21T19:36:44Z'
                    - '2019-06-12T20:32:21Z'
            properties:
              title: Common properties
              type: object
    stacCatalogue:
      title: STAC Catalog Specification
      description: 
        This object represents Catalogs in a SpatioTemporal Asset Catalog.
        This schema is deaply inspired on https://raw.githubusercontent.com/radiantearth/stac-spec/master/catalog-spec/json-schema/catalog.json
        Changes
        The link definition has been replaced by the one in OGC API Common.        
      type: object
      required:
      - stac_version
      - id
      - description
      - links
      properties:
        stac_version:
          title: STAC version
          type: string
          const: 0.8.0
          example: 0.8.0
        stac_extensions:
          title: STAC extensions
          type: array
          uniqueItems: true
          items:
            type: string
        id:
          title: Identifier
          type: string
          example: Daraa_mosaic_2019
        title:
          title: Title
          type: string
          example: Imagery from Daraa 2019
        description:
          title: Description
          type: string
          example: Catalog of imagery in coverage Daraa_mosaic_2019
        links:
          title: Links
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/link'
          example: 
          - rel: self
            href: https://tb15.cubewerx.com/cubewerx/cubeserv/op-stac/wmts/1.0.0/collections/Daraa_mosaic_2019/images
          - rel: root
            href: https://tb15.cubewerx.com/cubewerx/cubeserv/op-stac/wmts/1.0.0/collections/Daraa_mosaic_2019/images
          - rel: item
            href: https://tb15.cubewerx.com/cubewerx/cubeserv/op-stac/wmts/1.0.0/collections/Daraa_mosaic_2019/images/23
          - rel: item
            href: https://tb15.cubewerx.com/cubewerx/cubeserv/op-stac/wmts/1.0.0/collections/Daraa_mosaic_2019/images/5          
        summaries:
          $ref: '#/components/schemas/stacSummaries'
    stacSummaries:
      type: object
      additionalProperties:
        oneOf:
        - title: Stats
          type: object
          required:
          - min
          - max
          properties:
            min:
              title: Minimum value
              type:
              - number
              - string
            max:
              title: Maximum value
              type:
              - number
              - string
        - title: Set of values
          type: array
          minItems: 1
          items:
            description: Any data type could occur.
    stacAsset:
      type: object
      required:
      - href
      properties:
        href:
          title: Asset reference
          type: string
        title:
          title: Asset title
          type: string
        type:
          title: Asset type
          type: string
    stacProviders:
      type: array
      items:
        properties:
          name:
            title: Organization name
            type: string
            example: NGA
          description:
            title: Provider description
            type: string
            example: National Geospatial-Intelligence Agency
          roles:
            title: Organization roles
            type: array
            items:
              type: string
              enum:
              - producer
              - licensor
              - processor
              - host
          url:
            title: Homepage
            type: string
            format: url
            example: https://www.nga.mil
  parameters:
    imageId:
      name: imageId
      in: path
      description: local identifier of a image
      required: true
      schema:
        type: string